// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgsaewpvvajelntjzcuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnc2Fld3B2dmFqZWxudGp6Y3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzEwODksImV4cCI6MjA3MzcwNzA4OX0.xNknDKrQ1-7Px6ZfbPxj64ft-42xKaA98BFjzI5ORAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});